### ISSUE TITLE
"Clear Configuration" UI option doesn't work

### ISSUE THREAD

**Issue by MAHDTech** [certtools/intelmq-manager#79] opened 2016-06-03 07:13 UTC
- Click the "Configuration" tab
- Click "Clear Configuration" (config is cleared onscreen)
- Click "Save Configuration"

The blank configuration is not saved, if you browse to "monitor" tab, the existing bots are still there, and when you come back to the "Configuration" tab the old config has returned.

However, if you instead,
- Click the "Configuration" tab
- Click "Edit"
- remove all bots manually
- save

works fine.

Can anyone else confirm?

**Comment by sebix** [comment] 2016-06-05 21:38
I can confirm that the manager is not intuitive and misses handling of error messages. Tough we do not have developers to fix this in the near future :(

**Comment by sykaeh** [comment] 2016-11-09 20:59
I cannot reproduce this issue. @MAHDTech, can you confirm that you still have this issue with the most up-to-date version of the manager and intelmq?

**Comment by ondj** [comment] 2016-12-07 14:42
@MAHDTech Probably it was fixed in #86. Can you try it with current master?

**Comment by wagner-certat** [comment] 2017-08-22 14:07
not reproducible

**Closed by wagner-certat** 2017-08-22 14:07 UTC
Labels: bug, component: configuration, help wanted
