### ISSUE TITLE
There is an error in moniter page of any bot

### ISSUE THREAD

**Issue by fatecyx** [certtools/intelmq-manager#63] opened 2016-01-05 03:36 UTC
![qq 20160105113422](https://cloud.githubusercontent.com/assets/3907379/12107014/4cca8de8-b3a0-11e5-91ee-e63406af7c3e.png)

But the data is already in the file: /opt/intelmq/var/lib/bots/file-output/events.txt

**Comment by aaronkaplan** [comment] 2016-01-05 07:33
Hi @fatecyx, this looks as if the log file of the bot (see /opt/intelmq/var/log/* ) was truncated. Can you check please?

**Comment by fatecyx** [comment] 2016-01-05 09:08
@aaronkaplan 
I tried to deleted all the logs, reduced the bots, and restart them.
There is the logs.
It seems that every line is the '%time% - %module% - %LEVEL% - %INFO%'

[intelmqctl.log.txt](https://github.com/certtools/intelmq-manager/files/78193/intelmqctl.log.txt)
[file-output.log.txt](https://github.com/certtools/intelmq-manager/files/78194/file-output.log.txt)
[abusech-palevo-tracker-ips-parser.log.txt](https://github.com/certtools/intelmq-manager/files/78195/abusech-palevo-tracker-ips-parser.log.txt)
[abusech-palevo-tracker-ips-collector.log.txt](https://github.com/certtools/intelmq-manager/files/78196/abusech-palevo-tracker-ips-collector.log.txt)

**Comment by aaronkaplan** [comment] 2016-01-05 09:17
> On 05 Jan 2016, at 10:08, fatecyx <notifications@github.com> wrote:
> 
> @aaronkaplan
> I tried to deleted all the logs, reduced the bots, and restart them.
> There is the logs.
> It seems that every line is the '%time% - %module% - %LEVEL% - %INFO%'
> 
> intelmqctl.log.txt
> file-output.log.txt
> abusech-palevo-tracker-ips-parser.log.txt
> abusech-palevo-tracker-ips-collector.log.txt
> 

Yeah I see. So basically what happens is that intelmq-manager will try try to load the log files of all bots.
But if it does not exist or is truncated, then it will show this error message. Maybe it should be more tolerant to non-existing log files.

But it is basically a harmless error message.

Best,
a.

**Comment by fatecyx** [comment] 2016-01-05 09:26
No,No.
The logs are already existed now. But the error is still.

there have been some ip datas in the file-output.log, and the count of moniter is still 0

**Comment by sebix** [comment] 2016-01-05 09:31
> the count of moniter is still 0
The counter shows the messages in the queue, wanting to be processed by the next bot. This is not the number of already processed messages.

**Comment by fatecyx** [comment] 2016-01-05 09:41
Oh, I see.
But, why the log connot show in the moniter page? the log file is really already existed: 
'abusech-palevo-tracker-ips-parser.log' 
and 
'abusech-palevo-tracker-ips-collector.log'

**Comment by putsi** [comment] 2016-02-09 13:18
Make sure that the intelmq-manager can access the log file directory and the log files.
I had this same error when the log directory was accessible only for root user.

**Comment by sebix** [comment] 2016-02-09 14:07
> I had this same error when the log directory was owned by root-user and the directory permissions allowed only root-user to view log files.

See https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#install-1

**Comment by sebix** [comment] 2016-09-15 06:40
Duplicate of #69

**Closed by sebix** 2016-09-15 06:40 UTC
Labels: component: monitor
