### ISSUE TITLE
intelmq-manager start/stop does not work

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq-manager#42] opened 2015-02-25 12:26 UTC
Pressing Start/Stop in the Management tab does nothing.

Probably a permission problem?

**Comment by SYNchroACK** [comment] 2015-02-25 12:35
Yes, its a bug. What I do everytime i star the machine is:

```
mkdir /var/log/intelmq
mkdir /var/run/intelmq
chmod -R 700 /var/run/intelmq
chmod -R 700 /var/log/intelmq
chown -R intelmq.intelmq /var/run/intelmq
chown -R intelmq.intelmq /var/log/intelmq

chmod -R 770 /etc/intelmq/
chmod -R 700 /var/run/intelmq
chmod -R 700 /var/lib/intelmq
chmod -R 700 /usr/local/bin/intelmqctl
chmod -R 700 /var/log/intelmq

chown -R intelmq.intelmq /etc/intelmq/
chown -R intelmq.intelmq /var/run/intelmq
chown -R intelmq.intelmq /var/lib/intelmq
chown -R intelmq.intelmq /usr/local/bin/intelmqctl
chown -R intelmq.intelmq /var/log/intelmq
```

Of course, we need to commit a solution to do this automatically.

**Comment by aaronkaplan** [comment] 2015-02-25 12:36
does not fix it.

**Comment by SYNchroACK** [comment] 2015-02-25 12:45
```
mkdir /var/run/intelmq
chmod -R 700 /var/run/intelmq
chown -R intelmq.intelmq /var/run/intelmq
```

**Comment by SYNchroACK** [comment] 2015-02-25 12:52
So, its a problem on 'intelmqctl'

**Comment by Th4nat0s** [comment] 2015-05-26 21:19
I had issue only on "stop"... start is ok... could it been related ?

Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 413, in <module>
    x.run()
  File "/opt/intelmq/bin/intelmqctl", line 184, in run
    results = call_method(self.args.bot_id)
  File "/opt/intelmq/bin/intelmqctl", line 233, in bot_stop
    res = self.__bot_stop(bot_id, pid)
  File "/opt/intelmq/bin/intelmqctl", line 242, in __bot_stop
    stop_process(pid)
  File "/opt/intelmq/bin/intelmqctl", line 112, in stop_process
    p.send_signal(signal.SIGINT)
  File "/usr/local/lib/python2.7/dist-packages/psutil-2.1.1-py2.7-linux-x86_64.egg/psutil/__init__.py", line 258, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil-2.1.1-py2.7-linux-x86_64.egg/psutil/__init__.py", line 986, in send_signal
    self._send_signal(sig)
  File "/usr/local/lib/python2.7/dist-packages/psutil-2.1.1-py2.7-linux-x86_64.egg/psutil/__init__.py", line 975, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: (pid=69718)

**Comment by sebix** [comment] 2015-08-06 13:18
@Th4nat0s Does this issue still persist on current versions (v1.0-final branch of intelmq)?

**Comment by kralca** [comment] 2015-12-11 05:58
Today I have a similar problem. I can stop a bot in intelmq-manager, but I cannot start it. There are no errors in the logs, and I tracked it down to being a problem with running intelmqctl via sudo. For some reason that I cannot explain, the bot does not start when intelmqctl is run using the 'sudo -u intelmq' approach. You can very easily verify this for yourself. The bot starts fine if you 'sudo -iu intelmq' first and then run intelmqctl from the shell.

**Comment by kralca** [comment] 2015-12-11 06:30
This is related to #61.  The problem is that the environment variable INTELMQ_PYTHON is not set when intelmq is run via 'sudo -u intelmq'. I have tested the following solution (Ubuntu 14.04.3). No doubt there are other ways to achieve the same result.
1. add `INTELMQ_PYTHON=/usr/bin/python3.4` to /etc/environment
2. add `Defaults        env_file="/etc/environment"` to sudoers using visudo

**Comment by sebix** [comment] 2015-12-11 07:48
If `INTELMQ_PYTHON` is not set, the standard Python version is used (`python`), it is not necessary to run the software itself. This means that the bot was not able to start with Python 2.

**Comment by kralca** [comment] 2015-12-13 22:45
That makes sense. We are using the Python 3 version of intelmq as recommended in the installation. I changed the first line of intelmqctl to `#!/usr/bin/env python3` to make things work on Ubuntu since `python` will be Python 2 for a while - see https://wiki.ubuntu.com/Python/3. Is there a better way to use intelmq with Python 3? Using an alias for `python` will not solve the issues above with intelmq-manager.

**Comment by sebix** [comment] 2016-09-15 06:39
Duplicate of #69

**Closed by sebix** 2016-09-15 06:39 UTC
Labels: bug, component: management
