### ISSUE TITLE
broken link when clicking on monitor -> queue

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq-manager#170] opened 2018-09-03 14:55 UTC
When clicking on a queue name in the "monitor" tab, you will end up with a broken link.

example:

http://mydomain.com/?page=monitor  -> is the monitor page.

Clock on a link, example cymry-whois-expert, you will be redirected to 
http://mydomain.com/monitor.html?bot_id=cymru-whois-expert

You actually want to have an URL such as:
http://mydomain.com/?page=monitor&bot_id=cymru-whois-expert

I think this can be fixed very easily. It's probably just an adaptation in the template.

**Comment by wagner-certat** [comment] 2018-09-03 15:07
Looks like a duplicate of #157

Should be fixed in the maintenance and develop branch. Can you confirm this?

**Comment by e3rd** [comment] 2018-09-17 16:45
Hi, I've been out for three weeks.

I've looked into the code and whole buggy part is fixed in the `maintenance` branch and completely rewritten in the `develop` branch. When any of these branches gets merged into the `master`, lets close the issue.

**Closed** 2018-11-09 16:57 UTC
Labels: bug
